-*- org-src-preserve-indentation: t -*-
#+TITLE: Vimrc file
#+PROPERTY: header-args:vimrc :tangle vimrc :results none
#+PROPERTY: header-args:filetype :tangle filetype.vim :results none
#+OPTIONS: toc:2

* Header

This just puts a comment header in the generated vimrc file.

#+begin_src vimrc
" This file was generated from vimconfig.org by using org-babel-tangle.
" That file is 'tangled' to make this vimrc file which should be pointed to
" by a link '~/.vimrc -> $this_file'
#+end_src

* Fundamental
** Be iMproved

#+begin_src vimrc
set nocompatible              " be iMproved, required
filetype plugin indent on
#+end_src

** Remember position in file

This line can be found commented in the system vimrc file : =/etc/vim/vimrc=.
#+begin_src vimrc
autocmd BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal!  g'\"" | endif
#+end_src
I left out the =if has("autocmd")= because I have yet to encounter a version of
vim that does not have it.

*** Exception for commit messages

Git reuses =.git/COMMIT_EDITMSG= for when editing commit messages with the
editor.  In that context we always want the cursor to start on the first
line.  We do the same thing for the =git-rebase-todo= file that is used for
interactive rebases.

#+begin_src vimrc
autocmd BufReadPost COMMIT_EDITMSG,git-rebase-todo :0
#+end_src

** Indentation

*** General

#+begin_src vimrc
set autoindent
set list
#+end_src

*** 4 spaces for everything

Allways use 4 spaces, if a file does contain real =\t= characters, display them
4 spaces wide

#+begin_src vimrc
set tabstop=4       " Display width of \t character
set shiftwidth=4    " Indents will have a width of 4.
set softtabstop=4   " Sets the number of columns for a TAB.
set expandtab       " Expand TABs to spaces.
#+end_src

We use listchars to show unwanted whitespace characters: tabs are shown as =»~=
when space is the preferred indentation and leading spaces are shown as =»= in
=go= and =make= where real =\t= characters are the preferred indentation method.

#+begin_src vimrc
set listchars=tab:»~,extends:›,precedes:‹,nbsp:·,trail:·
#+end_src

*** Tabs for go and make

Display tabs 4 spaces wide and don't convert to spaces.

#+begin_src vimrc
autocmd FileType make,go setlocal tabstop=8 shiftwidth=8 softtabstop=0 noexpandtab
#+end_src

Change =listchars= to show indentation with spaces and display tabs normally.

Previous versions of vim did not have a =lead= element for =listchars= so there
was no way to differentiate between leading spaces and other spaces.  So in Vim
<9, for go and make, we use a =·= for all spaces which is not so unpleasant.

#+begin_src vimrc
if version >= 900
    autocmd FileType make,go setlocal listchars=tab:\ \ ,lead:·,trail:·,precedes:←,extends:→
else
    autocmd FileType make,go setlocal listchars=tab:\ \ ,space:·,trail:·,precedes:←,extends:→
endif
#+end_src

**** Alternative for leading whitespace in vim < 9

This [[https://stackoverflow.com/a/40498439][solution by rodrigo]] is an
alternative that I decided not to use but I'm documenting my use of it here
since I had to figure out some things to make it work.

Another solution is to highlight spaces at the beginning of the line.

We create a highlight group =WhiteSpaceBol=

#+begin_src vimrc :tangle no
highlight WhiteSpaceBol ctermbg=red
#+end_src

and have it match white space at the beginning of the line for Makefiles and
Go files.

#+begin_src vimrc :tangle no
autocmd FileType make,go match WhiteSpaceBol /^ \+/
#+end_src

For this to work, the definition of the highlight group needs to come after
the loading of the colorscheme in the =~/.vimrc= file and the =match= needs
to come after the highlight group has been defined.  Because it's in an
=autocmd=, it can come before in the =.vimrc= file.

If I wanted to use this, I would need to move the =highlight WhiteSpaceBol
ctermbg=red= somewhere else in the file.

However, I decided that I didn't like it that much and having =space:·= in
listchars works just fine.


*** Two spaces for yaml

#+begin_src vimrc
autocmd FileType yaml setlocal tabstop=2 shiftwidth=2 softtabstop=2 expandtab
#+end_src

*** Use AnsiEsc for =*.out= files

The plugin
[[https://github.com/powerman/vim-plugin-AnsiEsc][Ansi-Esc]]
provides the command =AnsiEsc= that hides ANSI escape codes and colors the file
according to these codes.  For file extensions that are likely to contain such
codes such log files, we call this function on opening the file.

#+begin_src vimrc
autocmd BufRead *.out,*.log :AnsiEsc
autocmd BufRead *.out,*.log setlocal nowrap
#+end_src

** Wrapping

*** Hard Wrapping
#+begin_src vimrc
set textwidth=0
#+end_src
See =:help textwidth= setting =textwidth= to a non-zero value activates
automatic hard wrapping while inserting.
#+begin_src vimrc
" This doesn't work but I tried it with autocmd filetype and it seemed to
" work
" au BufRead,BufNewFile *.md setlocal textwidth=80
" au BufRead,BufNewFile *.org setlocal textwidth=80
" au BufRead,BufNewFile *.txt setlocal textwidth=80
#+end_src

*** Visual wrapping

**** Configure visual wrapping

#+begin_src vimrc
set wrap
set wrapmargin=0
#+end_src

**** colorcolumn

I prefer to never have text auto-wrap except in prose formats (non-code).

This command colors the 80th column slightly differently so that I can avoid
going over 80 characters, but also allows me to go over when I feel like it
is peferable.

#+begin_src vimrc
set colorcolumn=80
#+end_src

**** Set j,k to move up and down visual lines

This makes =j,k= move up and down display lines instead of moving by logical
lines (i.e. defined by ='\n'=) in normal and visual modes.  In visual *line*
mode still selects logical lines but I prefer to have the cursor always move
the same way.

#+begin_src vimrc
nnoremap j gj
nnoremap k gk
vnoremap j gj
vnoremap k gk
#+end_src

** MISC

Keep the cursor 5 lines away from the top of the window.  Normally the window
doesn't start scrolling until the cursor reaches the very top or the very bottom
but with this, the text will start scrolling when the cursor gets within 5
lines of the top of the window.  Once you have it, you can't live with out it!

#+begin_src vimrc
set scrolloff=5
#+end_src

#+begin_src vimrc
syntax on
set hlsearch
set number
set showcmd " Display incomplete commands at the right
set backspace=indent,eol,start " Usual backspace behavior
set encoding=utf-8
#+end_src

** Leader key

#+begin_src vimrc
let mapleader = ' '
#+end_src

* Additional
** Color

#+begin_src vimrc
set t_Co=256 " Apparently this has to be set before setting the color scheme
#+end_src

In order to experiment with not using color in my shell and editors, I have
two environment variables which I set in my shell startup file
=__editor_grayscale= and =__shell_grayscale=.  With the =true-monochrome=
colorscheme, the color of the =colorcolumn= is red, so in that case, I
explicitly set its color.

#+begin_src vimrc
if $__editor_grayscale == ""
    colorscheme molokai " Requires https://github.com/tomasr/molokai
    packadd powerline-plugin
else
    colorscheme true-monochrome
    highlight ColorColumn ctermbg=236
endif
#+end_src

** Plugins
*** Markdown nested folding

Plugin : https://github.com/masukomi/vim-markdown-folding

#+begin_src vimrc
autocmd FileType markdown setlocal foldexpr=NestedMarkdownFolds()
#+end_src

*** Org

Plugins :
- https://github.com/jceb/vim-orgmode
- https://github.com/tpope/vim-speeddating (not the thing where you go to meet
  people, but a thing to work with dates really fast)

Org todo keywords
#+begin_src vimrc
let g:org_todo_keywords=['TODO', 'GTD-IN', 'GTD-ACTION', 'GTD-PROJECT', 'GTD-NEXT-ACTION', 'GTD-WAITING', 'GTD-SOMEDAY-MAYBE', 'FEEDBACK', 'VERIFY', '|', 'DONE', 'GTD-DONE', 'GTD-REFERENCE', 'GTD-DELEGATED']
#+end_src

Path to elisp backend
#+begin_src vimrc
let g:org_export_emacs="/usr/bin/emacs"
#+end_src

** Status line
*** Always show status line

2 means always

#+begin_src vimrc
set laststatus=2
#+end_src

*** New Powerline
**** Install instructions

These are the official instructions but this is not what I do.

https://powerline.readthedocs.io/en/latest/installation/osx.html#python-package

**** Using powerline

I use powerline with vim8's native plugin handling.

I put a link pointing to =$repo/powerline/bindings/vim= inside the
=~/.vim/pack/*/start=.

Make sure =laststatus=2= makes it always displayed.

**** Important note about macos

Adding powerline made vim hang and fail to start on my mac.  I figured out that
changing to a version of vim that has python3 support fixed my problem.

I did
#+begin_src shell
brew install --cask macvim
#+end_src
and made sure that this version of vim is the one being used.

*** Old powerline

Just added the submodule https//github.com/lokaltog/vim-powerline.  No need
to do anything else than make sure the =laststatus= is set to 2 (always).

Edit: I removed it but I am leaving this section here.  The new powerline made
my vim not start until I replaced it with macvim installed from homebrew.

The lokaltog one however doesn't need anything like that.

As far as I know, the problem only happens on mac and on the various linux
computers I have tried, the new powerline has not been an issue.

** Keys

*** Leaving insert mode

#+begin_src vimrc
inoremap jk <ESC>
#+end_src

**** Cursor position after leaving insert mode

99.99% of the time, I ended up pressing =l= after pressing =<ESC>= to leave
insert mode.

[[https://vim.fandom.com/wiki/Prevent_escape_from_moving_the_cursor_one_character_to_the_left#Programmatic_Alternative][This Vim Fandom answer]]
gives the solution used below and also tells you that if you want this this
behavior, then you dont care about consistency.  Hey Vim Fandom, you know
what's very consistent?  The fact that I always press =l= after leaving
insert mode!

#+begin_src vimrc
let CursorColumnI = 0 "the cursor column position in INSERT
autocmd InsertEnter * let CursorColumnI = col('.')
autocmd CursorMovedI * let CursorColumnI = col('.')
autocmd InsertLeave * if col('.') != CursorColumnI | call cursor(0, col('.')+1) | endif
#+end_src

Because of the nature of 'ESC' and the fact that terminals implement things
like function keys using =<ESC>[15~=, Vim waits a little while after <ESC>
has been received to see if something like =[15~= follows.

[[https://superuser.com/questions/1579208/delay-after-hitting-escape]]
[[https://vi.stackexchange.com/questions/16148/slow-vim-escape-from-insert-mode]]

This delay can be completely eliminated by telling vim that you will never
use such keys.  In that case, =ESC= will always mean that the user pressed
that key on the keyboard and there is no need for the delay.

#+begin_src vimrc :tangle no
set noesckeys
#+end_src

However I noticed that the arrow keys are implemented as an escape sequence.
Although I never use them, sometimes, I do them by mistake and the behavior
with =set noesckeys= is much more annoying than my =:echoerr "your mind is
weak"= things.

Instead, we can set =ttimeoutlen= to a very small value like 50ms and this is
short enough that we cannot notice it, but longer than the time between
successive keycodes sent by the terminal to communicate an arrow key.

#+begin_src vimrc
set timeoutlen=500 ttimeoutlen=50
#+end_src


*** Cursor position after paste

Normally, the cursor ends on the last char of the pasted text but most of the
time, you want it after the pasted text.  For example, =P= to paste before
the cursor then =D= to delete till end of line.

#+begin_src vimrc
nnoremap p pl
nnoremap P Pl
#+end_src

*** Scrolling

Up down move the cursor in one direction and scrolls the view in the other.
This has the effect that the cursor stays in the same place on the screen
which is a good behavior for scrolling.

#+begin_src vimrc
nnoremap <Up> <C-y>k
nnoremap <Down> <C-e>j
#+end_src

*** Make arrows print quotes from The Shadow (1994) with Alec Baldwin

#+begin_src vimrc
nnoremap <Left> <ESC>:echoerr "Your mind is weak."<CR>
nnoremap <Right> <ESC>:echoerr "Your mind is weak."<CR>

inoremap <Up> <C-O>:echoerr "Join me or die"<CR>
inoremap <Down> <C-O>:echoerr "The clouded mind sees nothing"<CR>
inoremap <Left> <C-O>:echoerr "Your mind is weak."<CR>
inoremap <Right> <C-O>:echoerr "The clouded mind sees nothing"<CR>
#+end_src

** Clipboard

Tested on MacOS with Vim 8+

Reference : =:help clipboard=

You typically don't have access to the system clipboard when using Vim over an
ssh connection.

#+begin_src vimrc
if $SSH_CLIENT == ""
    set clipboard=unnamed
else
    vmap <silent> <leader>y "xy<CR>:wviminfo! ~/.viminfo<CR>
    nmap <silent> <leader>p :rviminfo! ~/.viminfo<CR>"xp
endif
#+end_src

When we are over an SSH connection we map =xy= in visual mode to yank to the =x=
register and to update the viminfo file immediately.

And to paste, we map =xy= to reread the viminfo file immediately and then past
from the =x= register.

This shows a bit of how the vim clipboard works (I'm probably commiting a
gravesin by calling it "the vim clipboard").

The contents of registers do get stored in the =~/.viminfo= file but not when
we yank.  And the content of the =~/.viminfo= file is not read when we paste.

We can natively yank-paste between instances of Vim but we have to yank in
one instance then quit so the viminfo file gets updated, then if we start
another instance after we quit the first one, at its startup, it will read
the updated viminfo file which will know about the text we yanked.

Help on =wviminfo= shows that if =!= is not used, wviminfo will merge info of
the running instance with what is in the =viminfo= file.  If however =!= is
used, then stuff does get overwritten.

For this reason using =xy= and =xp= has the potiential to lose information in
the viminfo file that would normally not have been lost.  Therefore it is
better to create new mappings =xy= and =xp= instead of remapping =y= and =p=
to always do this trick.

** Break the habit of pressing =x= multiple times
#+begin_src vimrc
nnoremap <silent> xx :echoerr 'Pressing "x" more than once consecutively is a sign of weakness'<CR>
#+end_src

** Display % as . in Fortran

Fortran uses =object%attribute= to get a field of a struct (in Fortran they
don't call it a struct, I think they call it a type).

I made this as a joke back when I first started programming in Fortran.  Obviously
the real solution is to get used to the language.

#+begin_src vimrc
" Funny thing to show '%' as '.' in Fortran files
" autocmd FileType fortran set conceallevel=2
" autocmd FileType fortran call matchadd('Conceal', '%', 10, -1, {'conceal': '.'})
#+end_src

** YouCompleteMe

Code completion engine for Vim.

#+begin_src vimrc
" Technically version > 8.1.2269 but I only encounter either vim 8.0 or vim 9+
" so this is easier
if version >= 900
    " Silent makes it not complain if the package doesn't exits in
    " .vim/pack/*/opt/
    silent! packadd YouCompleteMe
    nnoremap gd :YcmCompleter GoToDefinition<CR>
endif
#+end_src

** Command to justify text

This loads a visual mode command =_j= that will justify a paragraph of text.

The usefulness of this is somewhat questionnable, but it's fun to have I
guess.

Note that the format the format option 't' (=formatoptions+=t=) may make a
difference.  I read somewhere that it was needed but I'm not sure in what
cases.  I don't want to erroeneously think that it is needed so I'm leaving
it in commented.

#+begin_src vimrc
runtime macros/justify.vim
" set formatoptions+=t
#+end_src

** Unhighlight searches

For 10 years, I've been doing =/asdf<CR>= to unhighlight searches.

This stops now! I'll try these few options and possibly just keep one when I
find which one I like best.

#+begin_src vimrc
nnoremap <leader>c :noh<CR>
nnoremap <ESC><ESC> :noh<CR>
nnoremap <C-l> :noh<CR><C-l>
#+end_src

** Switch tab settings
Defines two functions to set groups of indentation related settings.  Note that
vim functions are weird: it seems that I cannot access the value of an argument
in a =set= command.  Instead, I have to do =let &<option>=a:<argument>=
according  to [[https://vi.stackexchange.com/a/11534/7936][this stack overflow post]] and that's just one of the reasons why I
like Emacs LISP better than Vimscript.

These functions are useful for example when browsing code that is indented
using tabs 

=TabMode= displays tabs as =a:nb= spaces with and leading spaces are marked using
=listchars= disables =expandtab=.

#+begin_src vimrc 
function! TabMode(nb)
    setlocal listchars=tab:\ \ ,lead:·,trail:·,precedes:←,extends:→
    let &tabstop=a:nb    " Display width of \t character
    set noexpandtab      " Don't expand tabs to spaces
endfunction
#+end_src

=SpaceMode= sets my preferred settings for indentation: tabs are expanded and
leading tabs are displayed using =listchars=.

#+begin_src vimrc 
function! SpaceMode(nb)
    setlocal listchars=tab:»~,extends:›,precedes:‹,nbsp:·,trail:·
    let &tabstop=a:nb       " Display width of \t character
    let &shiftwidth=a:nb    " Indents will have a width of 4.
    let &softtabstop=a:nb   " Sets the number of columns for a TAB.
    set expandtab           " Expand TABs to spaces.
endfunction
#+end_src

And we add two shortcut commands to call these functions more easily.  I chose
the argument 8 for =TabMode= because of the Linux style guide and 4 for
=SpaceMode= because that matches my default settings.

#+begin_src vimrc
command Tabs :call TabMode(8)
command Spaces :call SpaceMode(4)
#+end_src
* Language specific commands

Fortran makes you write =use, intrinsic :: iso_fortran_env= for every
function or subroutine in a file instead of putting it at the top of the file
so you end up writing it all the time.  The same goes for =iso_c_bindings=
and =implicit none=.

#+begin_src vimrc
nnoremap <Space>ife ouse, intrinsic :: iso_fortran_env<ESC>==
nnoremap <Space>icb ouse, intrinsic :: iso_c_binding<ESC>==
nnoremap <Space>ino oimplicit none<ESC>==
#+end_src

* Filetype associations

This section generates the file =filetype.vim=.

#+begin_src filetype
" This file is generated by org-tangle'ing vimconfig.org using the command
" 'emacs --batch -l org --eval "(setq org-src-preserve-indentation t)" vimconfig.org -f org-babel-tangle'
if exists("did_load_filetypes")
  finish
endif
augroup filetypedetect
#+end_src


** Non-standard fortran file extensions

These extensions are used in conjunction with =s.cc= or =s.compile=.  These
wrappers do something different with the files based on the extension.
However these are not know by standard programs.

#+begin_src filetype
    autocmd BufRead,BufNewFile *.ftn,*.ftn90,*.cdk,*.cdk90,*.inc,*.hf set filetype=fortran
#+end_src

** '.dot' file from CMC

The =.dot= extension is used to indicate that the script in question is meant
to be sourced.  The extension is recognized by vim as 'dot graph'.  To
override this:

#+begin_src filetype
    autocmd BufRead,BufNewFile *.dot set filetype=sh
#+end_src

** CMC profile files
#+begin_src filetype
    autocmd BufRead,BufNewFile */.profile.d/*   set filetype=sh
    autocmd BufRead,BufNewFile */.profile.d/*   set filetype=sh
#+end_src
** Package file

Files meant to be sourced by my custom function =p.use= inspired by
François's function =f.use= which basically does
=source ~/.profile.d/interactive/pack/$1=

#+begin_src filetype
    autocmd BufRead,BufNewFile */.profile.d/interactive/pack/* set filetype=sh
#+end_src

** CMC maestro files

When we ask maestro open a listing, it will decompress the stored listing
into a file in some subdirectory of =/tmp/= name the file =masetro_something=
#+begin_src filetype
    autocmd BufRead,BufNewFile *.def,*/.suites/*/*.cfg,/tmp/phc001/*/maestro* set filetype=sh
#+end_src


#+begin_src filetype
augroup END
#+end_src

* Shell command to tangle

To tangle from the shell, use this command:
#+begin_src sh
emacs --batch -l org --eval "(setq org-src-preserve-indentation t)" FILE -f org-babel-tangle
#+end_src

Note where the =FILE= appears in the command.

It seems that it must appear before the =-f org-babel-tangle= argument.

The manual =man emacs= says this about =-f=, =-l=, =-e, --eval=:

#+begin_quote
The following options are Lisp-oriented (these options are processed in the
order encountered):
#+end_quote

Note the =(setq org-src-preserve-indentation t)= in the command.  For this to
apply when tangling this file from Emacs with =C-c C-v C-t=, the line
=-*- org-src-preserve-indentation: t -*-= sets the same variable to =t= for this
file only.  It must be the first line of the file otherwise it has no effect.
